- packages/oracle/src/event_source.rs
- packages/oracle/src/main.rs
Resolves #4, resolves #5 and resolves #9
> Make `EventSource` continuously poll protocol chain only.

- packages/oracle/src/event_source.rs
- packages/oracle/src/main.rs
> Remove tokio channel

- packages/encoding/src/lib.rs
- packages/oracle/Cargo.toml
- packages/oracle/config/dev/config.toml
- packages/oracle/config/prod/config.toml
- packages/oracle/src/emitter.rs
- packages/oracle/src/epoch_tracker.rs
- packages/oracle/src/event_source.rs
- packages/oracle/src/indexed_chain.rs
- packages/oracle/src/main.rs
- packages/oracle/src/metrics.rs
- packages/oracle/src/store/models.rs
- packages/oracle/src/store/store.rs
Set an appropriate configuration value for epoch duration in `config/dev/`. Depends on https://github.com/edgeandnode/block-oracle/pull/22.
> Fix epoch calculation

- packages/encoding/src/encoding/mod.rs
- packages/encoding/src/lib.rs
- packages/encoding/src/messages.rs
Closes #26. This was simpler than I thought :smile:
> Add support for encoding the Reset message

- packages/oracle/src/store/store.rs
those will be removed anyways, but since we are adjusting the new CI
we need to fix them.
> Fix store tests

- packages/oracle/config/dev/config.toml
- packages/oracle/config/prod/config.toml
- packages/oracle/src/config.rs
- packages/oracle/src/emitter.rs
- packages/oracle/src/event_source.rs
- packages/oracle/src/main.rs
- packages/oracle/src/protocol_chain.rs
This PR renames some configuration keys to more sensible names and introduces transaction confirmation parameters to the configuration file.
> Minor configuration tweaks

- .local/prelude.sh
This is a fix after #56, since it didn't really solve the issue.
> local environment: Wait for graph node 

- crates/oracle/src/main.rs
- crates/oracle/src/networks_diff.rs
- crates/oracle/src/subgraph.rs
- packages/subgraph/subgraph.yaml
> Better subgraph query error handling

- .local/.overmind.env
- .local/Procfile
- .local/deploy-contract.sh
- .local/graph-node.sh
- .local/hardhat.sh
- .local/postgres.sh
More explicit configuration and verbose output.
Also refreshes the postgres database between runs.
> Update overmind scripts

- crates/oracle/src/subgraph_state.rs
> Fix formatting

- crates/oracle-encoder/examples/samples.json
- crates/oracle-encoder/src/main.rs
> Add support for message blocks in `oracle-encoder`

- packages/subgraph/src/helpers.ts
- packages/subgraph/src/mapping.ts
- packages/subgraph/tests/payload.test.ts
This PR is a collection of focused and atomic commits, with no significant feature changes. They just serve as cleaning some things up after the huge refactoring #88.
> Leftovers cleanups from #88

- .dockerignore
- Dockerfile
The layering (and, subsequently, the build times) suck, but for now it's a start.
> Add a simple Dockerfile

- crates/encoding/src/lib.rs
> Remove assumption of monotonically increasing block numbers

- k8s/Dockerfile
> Attempt to cache `cargo-chef` installation pinpointing crate version

- crates/encoding/src/lib.rs
- crates/encoding/src/messages.rs
- crates/encoding/src/serialize.rs
- crates/oracle-encoder/examples/jsonnet-examples/06-register-networks-and-change-ownership.jsonnet
- crates/oracle-encoder/examples/jsonnet-examples/messages.libsonnet
- crates/oracle-encoder/src/main.rs
Closes https://github.com/graphprotocol/block-oracle/issues/144.
> Implement `ChangeOwnership` on the oracle side

- Cargo.lock
- crates/encoding/Cargo.toml
- crates/encoding/src/lib.rs
- crates/oracle/src/config.rs
- crates/oracle/src/contracts.rs
- crates/oracle/src/error_handling.rs
- crates/oracle/src/main.rs
- crates/oracle/src/models.rs
- crates/oracle/src/oracle.rs
- crates/oracle/src/subgraph.rs
- crates/xtask/src/message_samples.rs
This will make our CI pass all current checks, releasing us from alert fatigue.
> Address clippy lints

- crates/oracle/src/oracle.rs
This replaces the primitive type composition with a custom enum, for improved legibility.
> fix: flipped bollean logic in epoch detection

- crates/oracle/src/jrpc_utils.rs
Closes https://github.com/graphprotocol/block-oracle/issues/158.
We are using off-the-shelf `web3` with a custom JSON-RPC call that ignores fields that are Celo-incompatible.
To do before merging:
> Add support for Celo

- crates/encoding/src/lib.rs
- crates/oracle/src/networks_diff.rs
- crates/oracle/src/oracle.rs
> Encoder: Replace `swap_remove` with `remove` 

- .github/workflows/oracle.yml
Might re-add them in the future, once we figure out the pricing issue.
> Remove precompiled binaries

- crates/oracle/src/runner/oracle.rs
This prevents a deadlock between the Epoch Subgraph and the Block Oracle, in which the former would never leave the uninitialized state
> fix: prevent subgraph initialization deadlock condition

- crates/oracle/src/metrics.rs
- crates/oracle/src/runner/jrpc_utils.rs
Adds a new metric for counting JRPC failures.
> Monitor JRPC failures

- k8s/overlays/staging-mainnet/config.toml
- k8s/overlays/staging-mainnet/environment-variables.yaml
- latest approved list of indexed chains and their JRPC endpoints
- @graphprotocol Epoch Subgraph
> ci: update mainnet deployment configuration

- packages/subgraph/config/prod.json
- packages/subgraph/package.json
- packages/subgraph/src/constants.ts
- packages/subgraph/src/mapping.ts
- packages/subgraph/subgraph.yaml
Makes sure that preamble and permissions don't block the valid Council tx.
Needs to be refactored into a proper permission list fix
> fix: hotfix for mainnet

- packages/contracts/package.json
- packages/subgraph/package.json
Use a scope for the package names as other packages under graphprotocol.
> chore: add namespace to package names

- Cargo.lock
- crates/oracle/Cargo.toml
- crates/oracle/build.rs
- crates/oracle/proto/sf/blockmeta/v2/blockmeta.proto
- crates/oracle/src/blockmeta/blockmeta_client.rs
- crates/oracle/src/blockmeta/sf_blockmeta_client/sf.blockmeta.v2.rs
- crates/oracle/src/config.rs
- crates/oracle/src/main.rs
- crates/oracle/src/models.rs
- crates/oracle/src/runner/oracle.rs
- crates/oracle/src/subgraph.rs
- crates/oracle/test/config/config.sample.toml
- crates/oracle/test/config/indexed_chain_provider_via_env_var.toml
- crates/oracle/test/config/invalid_grpc_provider_url.toml
- k8s/overlays/staging-mainnet/config.toml
Adding Streaming fast [Blockmeta service client](https://github.com/streamingfast/blockmeta-service) to support blockmeta indexed chains.
> feat: add Blockmeta service client

- README.md
> docs: added a link to the license badge
