- packages/oracle/src/store/store.rs
This assumes that the last epoch is stored in the last sent DataEdge call.
Fixes #18.
> Fix epoch encoder persistence issues

- packages/oracle/Cargo.toml
- packages/oracle/src/config.rs
- packages/oracle/src/emitter.rs
- packages/oracle/src/indexed_chain.rs
- packages/oracle/src/main.rs
- packages/oracle/src/protocol_chain.rs
- packages/oracle/src/transport.rs
Used by `Indexed` and `Protocol` chain structs.
Cloning was necessary for some `web3` and `backoff` crate function calls,
as they won't take their parameters as references.
Fixes #15.
> Retries with exponential backoffs for JRPS calls

- packages/oracle/migrations/20220411_initial_schema.sql
- packages/oracle/migrations/20220503121545_message_types.sql
- packages/oracle/src/store/store.rs
This is probably insignificant, so feel free to close this PR without merging.
This PR transfers the relationship of `encoding_versions` and `message_types` from the latter to the `messages` table.
Currently, a `message_types` record is associated with a `encoding_versions` record.
After this PR, this relationship will be described by each row in the `messages` table.
The only benefit of this change is that it will prevent the `message_types` table from growing as `encoding_versions` grows.
> Decouple message types and encoding versions

- packages/encoding/src/lib.rs
- packages/oracle/Cargo.toml
- packages/oracle/config/prod/config.toml
- packages/oracle/src/emitter.rs
- packages/oracle/src/event_source.rs
- packages/oracle/src/indexed_chain.rs
- packages/oracle/src/main.rs
- packages/oracle/src/metrics.rs
- packages/oracle/src/store/models.rs
- packages/oracle/src/store/store.rs
- After every iteration in the main loop, we now persist the latest network deltas and block number.
- Removed the `enum Event` definition. I think it would make sense to reintroduce it if we had some sort of `next_event` method, but as long as we're only polling for the latest protocol chain block, we don't need it.
- More Prometheus metrics.
- We now have the latest block hash of all indexed chains.
This is my last big PR, now that we're getting to a more mature stage of the project, I'll try to keep contributions small and focused :)
> Persist network data, fetch block hash, better metrics

- packages/oracle/src/main.rs
- packages/oracle/src/protocol_chain.rs
Fixes #38.
This free function (and the whole module) should be later transferred to a definitive abstraction.
> Epoch Subgraph freshness check

- .gitignore
- packages/subgraph/abis/DataEdgeFull.json
- packages/subgraph/package.json
- packages/subgraph/schema.graphql
- packages/subgraph/src/constants.ts
- packages/subgraph/src/helpers.ts
- packages/subgraph/src/mapping.ts
- packages/subgraph/subgraph.yaml
- packages/subgraph/tests/decoding.test.ts
- packages/subgraph/yarn.lock
I'm proposing we should update the `block-oracle` branch to track the latest state of subgraph-related things. This allows us to query payloads, calls, message types, and networks.
> Sync Rust team's branch with the latest subgraph PoC

- .github/workflows/oracle.yml
- crates/encoding/src/lib.rs
When we updated the `encoding` API to be more pure, the unit tests weren't updated and they're now failing. This fix is quite superficial and doesn't test much of the interesting logic on the `CompressionEngine`, but it ought to be good enough for now.
> Fix encoding tests in `crates/encoding/src/lib.rs`

- packages/contracts/contracts/EventfulDataEdge.sol
- packages/contracts/test/eventful-dataedge.test.ts
For testing purposes we want a DataEdge contract that we can use with no need for traces. It's helpful for local environments using Hardhat that doesn't support traces (required by the call handlers).
- Adds an EventfulDataEdge contract
> Add a data edge contract that emits an event with the calldata

- .local/deploy-contract.sh
- packages/contracts/scripts/deploy-local.ts
This adds a dedicated hardhat deploy script (copy of the original,
just changed the contract's name) and updates a custom shell script to
call it instead.
> Update local environment setup for EventfulDataEdge

- .local/.overmind.env
- .local/block-oracle.sh
- .local/prelude.sh
We will have to update the `DEPLOYMENT_HASH` env every time the subgraph code changes, but I think this is already the case with Oracle's config file.
> local-environment: Make block-oracle wait for graph-node

- .local/.overmind.env
- .local/prelude.sh
Changes the URL of the subgraph in `.overmind.env` by name, not hash, so we don't have to update it every time the code changes.
> Refer to subgraph by name, not ID

- .local/.overmind.env
- .local/block-oracle.sh
- Cargo.toml
- crates/encoding/src/lib.rs
- crates/oracle/Cargo.toml
- crates/oracle/src/config.rs
- crates/oracle/src/graphql/query.graphql
- crates/oracle/src/graphql/schema.graphql
- crates/oracle/src/main.rs
- crates/oracle/src/subgraph.rs
This PR builds the necessary foundations for transitioning the state management system from SQLite to the subgraph. This PR doesn't alter the state of the oracle, it simply queries for relevant information from the subgraph and prints them out after every iteration in the main loop. We're using `graphql_client`.
> MVP: query the subgraph

- .local/block-oracle.sh
- .local/graph-node.sh
For some reason, calling `cargo run` after `cargo build` seems to trigger compilation again.
> Don't use `cargo run`

- .local/prelude.sh
This accounts for premature deployments.
> Add another graph-node readiness check

- crates/oracle/src/emitter.rs
- crates/oracle/src/epoch_tracker.rs
- crates/oracle/src/error_handling.rs
- crates/oracle/src/event_source.rs
- crates/oracle/src/main.rs
- crates/oracle/src/subgraph_state.rs
This introduces the `MainLoopFlow` trait that allows the main Oracle loop to be controlled by specific component errors.
This was implemented over the present "error enum tree", which might not be optimal for this idea.
So, we might want to refactor (or even erase) the `crate::Error` type in favor of generics.
Depends on #69.
*Please view this as an experiment on error handling design/organization for this project.*
> Let component errors dive the main loop

- crates/encoding/src/lib.rs
- crates/oracle-encoder/Cargo.toml
- crates/oracle-encoder/examples/samples.json
- crates/oracle-encoder/src/main.rs
```
$ cargo build
$ ./target/debug/oracle-encoder --json-path crates/oracle-encoder/examples/samples.json
```
@juanmardefago  I'm also sending you the binary over slack so you can just run `oracle-encoder --json-path crates/oracle-encoder/examples/samples.json` without having to go through Cargo.
> Add a simple message encoder script

- .gitignore
- crates/oracle-encoder/examples/01-empty-blocknums.jsonnet
- crates/oracle-encoder/examples/02-register-networks-and-set-block-numbers-same-payload.jsonnet
- crates/oracle-encoder/examples/03-register-networks-and-set-block-numbers.jsonnet
- crates/oracle-encoder/examples/04-register-multiple-and-set-block-numbers-thrice.jsonnet
- crates/oracle-encoder/examples/05-register-multiple-and-unregister.jsonnet
- crates/oracle-encoder/examples/Makefile
- crates/oracle-encoder/examples/messages.libsonnet
This PR includes [`jsonnet`](https://jsonnet.org/learning/tutorial.html) files for generating `oracle-encoder` sample JSON data.
To compile the JSON files, just `cd` into `./crates/oracle-encoder/examples` and run `make`.
> Oracle encoder example files

- crates/oracle/Cargo.toml
- crates/oracle/data-edge-abi.json
- crates/oracle/src/config.rs
- crates/oracle/src/emitter.rs
- crates/oracle/src/main.rs
- crates/oracle/src/protocol_chain.rs
This removes a lot of (now) unnecessary code from both the Emitter and ProtocolChain components.
Fixes #104
> Use DataEdge contract ABI instead of manually crafting transactions

- packages/contracts/contracts/DataEdge.sol
- packages/contracts/contracts/EventfulDataEdge.sol
- packages/contracts/test/dataedge.test.ts
- packages/contracts/test/eventful-dataedge.test.ts
`eslint` had to be toggled off for lines with a semi-colon, as removing it caused `prettier-js` to raise errors.
`solhint` complained about the fallback function not being payable, so we turned it payable instead of suppressing that rule.
@abarmat, do you see making the fallback function payable as a problem? Otherwise, I can edit the `.solhint.json` file to ignore that rule.
Those lints are failing git pre-commit hooks, so fixing those will help us not having to disable commit checks for every commit :sweat:
> fix: address warnings for eslint and solhint

- crates/encoding/Cargo.toml
- crates/encoding/src/messages.rs
- crates/oracle/src/diagnostics.rs
- crates/oracle/src/main.rs
- `encoding` crate: Manual `fmt::Debug` impl. for `BlockPtr` that uses the `0x...` format for the block hash field.
- `oracle` crate: Added a helper `hex_string` function in the `diagnostics` module.
This PR is not exhaustive, so we might need to implement this standard for other log messages and types as we go.
> style: use hex strings instead of number arrays when logging bytes

- crates/oracle/config/test/indexed_chain_provider_via_env_var.toml
- crates/oracle/config/test/invalid_jrpc_provider_url.toml
- crates/oracle/src/config.rs
The current problem we have is that users are required to submit a TOML configuration file which might contain sensitive information. Getting this sort of data from environment variables would be much better. This is the approach we're taking:
When a configuration file lists an invalid URL as a provider, the oracle will automatically try to read the environment variable with such name and parse that as a URL. E.g.:
```toml
[indexed_chains]
"eip155:77" = "JRC_PROVIDER_EIP155_77"
"eip155:99" = "https://example.com"
```
Possible future improvements:
- Use custom, `serde`-compatible types to achieve this result, rather than having to explicitly call a helper function.
- More testing.
> Allow setting JSON-RPC providers via env. vars.

- crates/oracle/src/config.rs
As per title, no functional changes.
> Fix a warning with `allow(unused)`

- k8s/Dockerfile
Trying again with Debian, because `cargo-chef` plays nicer with it.
> Attempt `cargo-chef` caching on Debian

- crates/oracle/src/graphql/query.graphql
This is a temporary workaround as Graph Node don't support ordering by child entities yet.
In the future, we could revert this commit and order by the nested `epochNumber` field.
> feat: update canonical graphql query

- crates/oracle/config/staging/config.toml
This fix will only be necessary while we don't have access to the Epoch Manager.
> fix: emulate a longer epoch duration

- crates/oracle/src/config.rs
- crates/oracle/src/graphql/query.graphql
- crates/oracle/src/graphql/schema.graphql
- crates/oracle/src/jrpc_utils.rs
- crates/oracle/src/oracle.rs
- crates/oracle/src/subgraph.rs
This is the first part of freshness module integration. For now, we're only detecting subgraph freshness and not doing anything about it besides logging relevant information. A subsequent PR will cause an `Error` to be thrown and make the oracle wait some time before polling again.
> Freshness detection, part I

- crates/encoding/src/lib.rs
- crates/encoding/src/messages.rs
- crates/oracle-encoder/src/main.rs
- crates/oracle/src/jrpc_utils.rs
- crates/oracle/src/main.rs
- crates/oracle/src/models.rs
- crates/oracle/src/networks_diff.rs
- crates/oracle/src/oracle.rs
- crates/oracle/src/subgraph.rs
- Favor `BTreeMap` instead of `HashMap`.
- Improved return types: `get_latest_block` doesn't return `Ok(None)` anymore; rather, `None` is now translated into a `web3::Error` which would only ever be caused by a faulty JRPC provider.
- `get_latest_blocks` now has a `web3::Result` per chain, rather than failing the whole function call whenever a single `Web3` query fails.
- Faster, cheaper, and simpler `calls_in_block_range` by using [`Eth::block_with_txs`](https://docs.rs/web3/latest/web3/api/struct.Eth.html#method.block_with_txs) rather than [`Eth::block`](https://docs.rs/web3/latest/web3/api/struct.Eth.html#method.block) + [`Eth::transaction`](https://docs.rs/web3/latest/web3/api/struct.Eth.html#method.transaction).
- Less redundant logging. I've removed logs there were redundant (e.s. …
> Integrate freshness check module with Oracle::run and fail gracefully upon indexed chains' JRPC failure

- crates/oracle/src/main.rs
- crates/oracle/src/subgraph.rs
At the present state, the oracle doesn't react at all to subgraph failure and instead simply keeps polling without additional wait times. This is the correct behavior in some circumstances (e.g. connectivity issues aka `SubgraphQueryError::Transport`) but not others (e.g. failed subgraph, cause we can't do nothing about it).
This PR sets a 1 minute wait for connectivity issues, and 10 minutes for other subgraph failures.
> Set appropriate wait times upon subgraph failure

- crates/encoding/src/lib.rs
- crates/encoding/src/messages.rs
The fix is easy enough. We're supposed to set a zero increment for all networks that don't have a block number update, but were doing the exact opposite due to a faulty conditional; i.e. setting a zero increment for all networks that *did* have a block number update.
Includes a regression test.
Closes https://github.com/graphprotocol/block-oracle/issues/162.
> Fix zero'd block number updates from the oracle

- crates/encoding/src/lib.rs
Closes https://github.com/graphprotocol/block-oracle/issues/159. The bug was fixed already with https://github.com/graphprotocol/block-oracle/pull/168, but now we're including a regression test for this case as well.
> Regression test for skipped block updates

- crates/encoding/src/lib.rs
- crates/oracle/src/oracle.rs
Closes #https://github.com/graphprotocol/block-oracle/issues/32.
> Make sure `Encoder` state is modified appropriately every time we send messages

- crates/oracle/src/main.rs
Currently, the Oracle sleeps twice: both as a response to a recoverable error and by the end of each iteration cycle. 
This fix makes it jump back to the start of the main loop right after sleeping due to recoverable errors.
> fix: prevent the oracle from sleeping twice when handling errors

- Cargo.lock
- crates/oracle/Cargo.toml
- crates/oracle/src/oracle.rs
- crates/oracle/src/resources/test-response-subgraph-with-data.json
- crates/oracle/src/subgraph.rs
Now that we have a better idea about exactly what kind of subgraph state transitions we need,  we can remove unneeded transition logic from `SubgraphStateTracker`. State retention across refreshes is thrown away in favor of a simpler interface `Result<Option<T>, E>`, akin to `SubgraphApi`.
Also including a new unit test which tests the `GlobalState` deserialization logic.
@tilacog welcoming feedback before merging this, if you have any.
> Reduce responsabilities of `SubgraphStateTracker`

- crates/encoding/src/lib.rs
- crates/oracle/src/oracle.rs
This PR splits the internal pipeline of `CompressionEngine` into two stages, thus making a clear distinction between stateful compression and encoding. This allows for logging the intermediate, compressed byproduct before sealing the binary payload, which is obscure and obviously hard to read when glancing at the logs.
> Log compressed messages before encoding

- Cargo.lock
- crates/oracle-encoder/Cargo.toml
- crates/oracle-encoder/src/main.rs
- crates/xtask/src/main.rs
- crates/xtask/src/message_samples.rs
This PR adds the `--calldata` argument to the `oracle-encoder` program, allowing it to output the calldata instead of just the payload.
> `oracle-encoder`: Output calldata

- k8s/compose/docker-compose.yml
- packages/contracts/hardhat.config.ts
There was a typo in the hardhat configuration, and the `rm /pgdata/` command was useless.
The recommended way of using fresh volumes without creating new containers is stated in the related #166 PR.
> docker compose: Fix hardhat config and update postgres command

- Cargo.lock
- crates/oracle/Cargo.toml
- crates/oracle/src/config.rs
- crates/oracle/src/contracts.rs
- crates/oracle/src/lib.rs
- crates/oracle/src/main.rs
- crates/oracle/src/metrics.rs
- crates/oracle/src/oracle.rs
- k8s/compose/docker-compose.yml
- k8s/compose/prometheus/config.yaml
This PR lays out the foundation for Prometheus instrumentation:
1. a `&'static` metrics registry _(done mainly by @neysofu in previous commits)_.
2. a `hyper` HTTP server that serves Prometheus gathered metrics, running concurrent to Oracle's main loop.
3. a POC metric + instrumentation for tracking the current epoch, both at the Epoch Manager contract and the Epoch Subgraph.
4. a docker-compose entry and configuration for a `prometheus` service.
> Basic Prometheus monitoring 

- crates/oracle/src/main.rs
- crates/oracle/src/networks_diff.rs
- crates/oracle/src/oracle.rs
Makes the Oracle not send a `RegisterNetworks` message in the advent of a new epoch.
Diffing is still performed because a configuration error is returned if there are any differences between the configured and registered networks.
Fixes #190.
> Don't send `RegisterNetworks` msg, fail on indexed chain diff

- crates/oracle/src/metrics.rs
The correct unit for this metric is seconds, not nanoseconds
> fix: wrong metric units

- crates/oracle/src/metrics.rs
- crates/oracle/src/subgraph.rs
With this, we can monitor if the Epoch Subgraph has any indexing errors.
As follow-up work, we should be able to monitor invalid Payloads.
> feat: add a subgraph health metric

- Cargo.lock
- crates/oracle/Cargo.toml
- crates/oracle/src/metrics.rs
- crates/oracle/src/runner/mod.rs
This PR refactors the metrics server to use `warp`, which removes some boilerplate code, specially when dealing with paths.
The metrics are now exposed at `/metrics` instead of `/`.
> Warp metrics server

- Cargo.lock
- crates/oracle/Cargo.toml
- crates/oracle/src/config.rs
- crates/oracle/src/contracts.rs
- crates/oracle/src/main.rs
- crates/oracle/src/runner/mod.rs
- crates/oracle/src/runner/oracle.rs
- crates/oracle/src/runner/transaction_monitor.rs
- crates/oracle/src/subgraph.rs
- crates/xtask/src/message_samples.rs
- k8s/compose/config.toml
- k8s/compose/contracts/seed-then-set-automining-interval.js
- k8s/compose/docker-compose.yml
This PR introduces:
- The `TransactionMonitor` component, which is used by the `Contracts` module.
- A new configuration table labeled `transaction_monitoring`, where we can set all parameters that govern it.
---
**Todo:**
> Transaction Monitoring

- crates/oracle/src/runner/oracle.rs
This will update the ETH balance metric sooner, preventing any false alarms related to that metric.
> fix: check owner ETH balance earlier

- crates/encoding/src/serialize.rs
- crates/oracle/src/metrics.rs
- crates/oracle/src/runner/oracle.rs
I have been seeing `9223372036854776000` in Grafana panels across all oracles, most likely caused by this bug.
I also added the unit name to the metric for explicitness.
> fix: bad math to check if a i64 can hold a wallet balance
